spring:
  application:
    name: StoreReserve

  datasource:
    url: jdbc:mysql://localhost:3306/store_reservation
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method  # 메서드 정렬 (optional)
    disable-swagger-default-url: true  # 기본 경로 비활성화 (optional)